2023
designunit/unit4 pull request #90
Opened 2023-02-02 16:01 UTC by manhir

no new projects, some changes to base pages

2023-02-03 12:24 UTC, tmshv requested changes

2023-02-03 12:24 UTC, tmshv commented on src/components/UnitCanvas/index.tsx
> +/* eslint-disable @next/next/no-img-element */
нинада мьютить еслинт

2023-02-06 15:45 UTC, tmshv requested changes
подмержий последний мастер, я там понадобавлял

2023-02-06 17:32 UTC, manhir commented
подмержил, завтра исправлю ес-линты и можно будет закрывать

2023-02-16 18:55 UTC, tmshv approved these changes

2023-02-16 19:29 UTC, merged